-- Create Banks table
CREATE TABLE Banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    location VARCHAR2(255),
    established_year NUMBER(4)
);

-- Create Reviews table
CREATE TABLE Reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id NUMBER NOT NULL,
    reviewer_name VARCHAR2(255),
    review_text CLOB,
    review_date DATE,
    rating NUMBER(2,1), -- e.g., 4.5
    FOREIGN KEY (bank_id) REFERENCES Banks(bank_id)
);

 
